apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 10m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    commit: b6b18427a5fc9b5b7540cf6d0843afd5cf7f9b56
