apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    commit: ae8c39e5967d5c95c4fb17fbf4b0d0635a83769b
  sparseCheckout:
    - script/helm/garage
