apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    commit: d1333c172939d8d29d09c939e68c270458ef68c5
  sparseCheckout:
    - script/helm/garage
